#!/bin/bash

OLD_EMAIL="$1"
NEW_EMAIL="$2"
BRANCHSPEC="$3"

git filter-branch -f --env-filter "
if [ \"\$GIT_AUTHOR_EMAIL\" = \"$OLD_EMAIL\" ];
then
    export GIT_AUTHOR_EMAIL=\"$NEW_EMAIL\";
fi
if [ \"\$GIT_COMMITTER_EMAIL\" = \"$OLD_EMAIL\" ];
then
    export GIT_COMMITTER_EMAIL=\"$NEW_EMAIL\";
fi
" "$BRANCHSPEC"
