#!/bin/bash

if [ $# -lt 1 ]; then
	echo "Expected submodule as argument"
	exit 1
fi
submodule=$1

branch="master"
if [ $# -gt 1 ]; then
	branch="$2"
fi

git submodule status $submodule >/dev/null
ret=$?
if [ $ret -ne 0 ]; then
	exit 1
fi

git status --porcelain | grep -E "^M" >/dev/null
ret=$?
if [ $ret -ne 1 ]; then
	echo "There are staged changes, aborting"
	exit 1
fi

curdir=`pwd`
cd $submodule
git checkout $branch
git pull --rebase
cd $curdir
summary=`git submodule summary $submodule`
git add $submodule
msg="bump $submodule

$summary"
git commit -m "$msg"
